In [2]:
import pandas as pd
r_df=pd.DataFrame({
    'data':['x','y','z','x','y'],
    'key':range(5)
})

In [18]:
r_df

data  key
0    x    0
1    y    1
2    z    2
3    x    3
4    y    4

In [28]:
l_df=pd.DataFrame({
    'data':['x','y']},index=['x','y']
)

In [29]:
l_df

data
x    x
y    y

In [34]:
import numpy as np
arr1=np.arange(9).reshape(3,3)

In [35]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [43]:
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [47]:
ar=np.random.randn(3,2)

In [48]:
ar

array([[ 1.01234729,  1.12253595],
       [-0.37929635, -0.05540716],
       [-1.54763007,  0.36049729]])

In [57]:
ser1=pd.Series([2,np.nan,4,5],
              index=['x','y','z','w'])

In [58]:
ser1

x    2.0
y    NaN
z    4.0
w    5.0
dtype: float64

In [59]:
ser2=pd.Series([10,30,4,50],
              index=['x','y','z','w'])

In [60]:
ser2

x    10
y    30
z     4
w    50
dtype: int64

In [62]:
 pd.Series(np.where(pd.isnull(ser1),ser2,ser1),index=ser1.index)

x     2.0
y    30.0
z     4.0
w     5.0
dtype: float64

In [64]:
ser1.combine_first(ser2)

x     2.0
y    30.0
z     4.0
w     5.0
dtype: float64

In [67]:
odd_df=pd.DataFrame({'x':[2,3,np.nan,5],
                   'y':[45,43,43,np.nan],
                   'z':[np.nan,8,9,7]})

In [68]:
even_df=pd.DataFrame({'x':[2,np.nan,6,5,4],
                     'y':[90,87,np.nan,2,1]})

In [69]:
odd_df

x     y    z
0  2.0  45.0  NaN
1  3.0  43.0  8.0
2  NaN  43.0  9.0
3  5.0   NaN  7.0

In [70]:
even_df

x     y
0  2.0  90.0
1  NaN  87.0
2  6.0   NaN
3  5.0   2.0
4  4.0   1.0

In [71]:
odd_df.combine_first(even_df)

x     y    z
0  2.0  45.0  NaN
1  3.0  43.0  8.0
2  6.0  43.0  9.0
3  5.0   2.0  7.0
4  4.0   1.0  NaN

In [83]:
data=pd.DataFrame(np.arange(8).reshape(2,4),
                 index=pd.Index(['lf','sf'],name='city'),
                 columns=pd.Index(['a','b','c','d'],name='letters'))

In [84]:
data

letters  a  b  c  d
city               
lf       0  1  2  3
sf       4  5  6  7

In [85]:
data1=data.stack()

In [86]:
data1

city  letters
lf    a          0
      b          1
      c          2
      d          3
sf    a          4
      b          5
      c          6
      d          7
dtype: int32

In [87]:
data1=data1.unstack()

In [88]:
data1

letters  a  b  c  d
city               
lf       0  1  2  3
sf       4  5  6  7

In [89]:
ser1=pd.Series([1,2,3],index=['a','b','c'])

In [90]:
ser2=pd.Series([5,6,7],index=['x','y','z'])

In [91]:
dat=pd.concat([ser1,ser2],keys=['alpha','beta'])

In [92]:
dat

alpha  a    1
       b    2
       c    3
beta   x    5
       y    6
       z    7
dtype: int64